#include "FluxoraCore/Services/ModOrganizerProfileOrderService.hpp"

#include "TestFilesystem.hpp"

#include <gtest/gtest.h>

namespace fluxora::tests
{
    TEST(ModOrganizerProfileOrderServiceTests, ReadsModlistWithSeparatorsEnabledStateAndPriorityOrder)
    {
        TempDirectory temp;
        const std::filesystem::path profile = temp.path() / L"profiles" / L"Default";
        writeTextFile(
            profile / L"modlist.txt",
            "# This file was automatically generated by Mod Organizer.\n"
            "+Unofficial Patch\n"
            "-Visuals_separator\n"
            "-SkyUI\n"
            "+BodySlide\n"
            "+SkyUI\n"
            "*DLC: Dawnguard.esm\n");

        const ModOrganizerProfileOrder order = ModOrganizerProfileOrderService::read(profile);

        ASSERT_EQ(order.items.size(), 4U);
        EXPECT_EQ(order.items[0].kind, L"mod");
        EXPECT_EQ(order.items[0].folderName, L"BodySlide");
        EXPECT_EQ(order.items[1].kind, L"mod");
        EXPECT_EQ(order.items[1].folderName, L"SkyUI");
        EXPECT_EQ(order.items[2].kind, L"separator");
        EXPECT_EQ(order.items[2].separatorTitle, L"Visuals");
        EXPECT_EQ(order.items[3].kind, L"mod");
        EXPECT_EQ(order.items[3].folderName, L"Unofficial Patch");

        ASSERT_EQ(order.enabledByFolder.size(), 3U);
        EXPECT_TRUE(order.enabledByFolder.at(L"bodyslide"));
        EXPECT_FALSE(order.enabledByFolder.at(L"skyui"));
        EXPECT_TRUE(order.enabledByFolder.at(L"unofficial patch"));
    }

    TEST(ModOrganizerProfileOrderServiceTests, MissingModlistReturnsEmptyOrder)
    {
        TempDirectory temp;

        const ModOrganizerProfileOrder order =
            ModOrganizerProfileOrderService::read(temp.path() / L"profiles" / L"Default");

        EXPECT_TRUE(order.items.empty());
        EXPECT_TRUE(order.enabledByFolder.empty());
    }
}
